# Change these first
owner: holty07 
repo: Immerse-Uptime-Monitor 

sites:
  - name: Immerse Marketing
    url: https://immersemarketing.com.au
  - name: ALC Training (AU)
    url: https://alctraining.com.au
  - name: Billie Bob
    url: https://billiebob.com.au
  - name: Briggins
    url: https://www.briggins.com.au
  - name: Coral Covey
    url: https://coralcovey.com
  - name: CWBTS
    url: https://cwbts.com.au
  - name: Disability and Injury Services
    url: https://disabilityandinjuryservices.com.au
  - name: Farm Fresh Fundraising
    url: https://farmfreshfundraising.com.au
  - name: Fiona Schofield Millinery
    url: https://fionaschofieldmillinery.com.au
  - name: Holt Plumbing
    url: https://holtplumbing.com.au
  - name: JSM Accounting
    url: https://jsmaccounting.com.au
  - name: Longenergy
    url: https://longenergy.com.au
  - name: Need2Heal
    url: https://need2heal.com.au
  - name: Ninox EMS
    url: https://ninoxems.com
  - name: Pets.com.au
    url: https://pets.com.au
  - name: Pipers World
    url: https://pipersworld.com.au
  - name: Quiet Network
    url: https://quietnetwork.com.au
  - name: Snacktacular
    url: https://snacktacular.com.au
  - name: Sunny Coast Plumbing
    url: https://sunnycoastplumbing.com.au

status-website:
  cname: uptime.immersemarketing.com.au
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Immerse Monitoring
  introTitle: "A GitHub powered uptime monitor for Immerse Marketing Clients"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/holty07/Immerse-Uptime-Monitor).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: slack
    url: "$SLACK_WEBHOOK_URL"
